name: Publish NPM

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14.0
                  registry-url: 'https://registry.npmjs.org/'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: '9.14.x'
                  run_install: true

            - name: Run tests
              run: pnpm run test

    publish:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Fetch full history for Changesets

            - name: Check version changes
              id: check
              run: |
                  CURRENT_VERSION=$(jq -r .version package.json)
                  LATEST_TAG=$(git describe --tags --abbrev=0 2> /dev/null || echo "v0.0.0")
                  echo "Latest tag $LATEST_TAG"

                  LATEST_VERSION=${LATEST_TAG#v}

                  if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ]; then
                      echo "Version changed"
                      echo "version_changed=true" >> $GITHUB_OUTPUT
                      echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
                  else
                      echo "Version not changed"
                      echo "version_changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22.14.0
                  registry-url: 'https://registry.npmjs.org/'

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: '9.14.x'
                  run_install: true

            - name: Build
              if: steps.check.outputs.version_changed == 'true'
              run: pnpm run build

            - name: Publish to NPM
              if: steps.check.outputs.version_changed == 'true'
              run: npm publish --access public --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Tag release
              if: steps.check.outputs.version_changed == 'true'
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git tag -a "v${{ steps.check.outputs.new_version }}" -m "Release v${{ steps.check.outputs.new_version }}"
                  git push origin "v${{ steps.check.outputs.new_version }}"

            - name: Merge main back into develop
              if: steps.check.outputs.version_changed == 'true'
              run: |
                  git fetch origin
                  git checkout develop
